on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: publish Xaringan presentations

jobs:
  publish:
    runs-on: ubuntu-18.04
    env:
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/bionic/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        id: install-r

      - uses: r-lib/actions/setup-pandoc@v1
      
      - name: "[Stage] [Linux] Install required system libs"
        if: runner.os == 'Linux'
        run: sudo apt install libcurl4-openssl-dev libgit2-dev
      
      - name: "[Custom block] [Linux] Install spatial libraries"
        if: runner.os == 'Linux'
        run: sudo apt-get install libgdal-dev libproj-dev libgeos-dev libudunits2-dev

      - name: Install dependencies
        run: |
          install.packages("sf")
          install.packages("xaringan")
          install.packages("xaringanthemer")
          install.packages("devtools")
          install.packages("tidyverse")
          install.packages("leaflet")
          install.packages("leaflet.extras")
          devtools::install_github("rstudio/fontawesome")
          devtools::install_github("gadenbuie/xaringanExtra")
        shell: Rscript {0}
        
      - name: Build xaringan presentation
        run: |
          Rscript -e 'rmarkdown::render("slide/index.Rmd", output_file = "output/index.html")'
       
      - name: Copy css + HTMLwidgets
        run: |
          ls 
          cp slide/output/* public/output 
          cp slide/meliodas.css public/meliodas.css
          cp slide/default.css public/default.css
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
